name: 'Test Pyproject'
description: 'Runs pytest on working_dir/tests. Optionally checks that chronos services are accessible'
inputs:
  working_directory:
    default: '.'
  pytest_args:
    default: ""
runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: AuroTFP/aurotfp-github-actions/.github/actions/setup-aws-creds@master
      with:
        aws_role: ${{ inputs.aws_role }}
        aws_region: ${{ inputs.aws_region }}

    - run: pytest ${{ inputs.working_directory }}/tests ${{ inputs.pytest_args }}
      shell: bash
      env:
        DOCKER_INTERPRETER: TRUE
