name: 'Test Pyproject'
description: 'Runs pytest on working_dir/tests. Optionally checks that chronos services are accessible'
inputs:
  working_directory:
    default: '.'
  pytest_args:
    default: ""
  aws_role:
    default: null
  aws_region:
    default: null
runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      if: ${{ inputs.aws_role != null && inputs.aws_region != null }}
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}

    - run: pytest ${{ inputs.working_directory }}/tests ${{ inputs.pytest_args }}
      shell: bash
      env:
        DOCKER_INTERPRETER: TRUE
