name: 'Publish Wheel'
description: 'TBD'
inputs:
  working_directory:
    required: false
    default: '.'
    type: string
  artifact_name:
    required: true
    type: string
  tag:
    required: true
    type: string
  destination_url:
    required: true 
    type: string
  GH_TOKEN:
    required: true
  TWINE_USERNAME:
    required: true
  TWINE_PASSWORD:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.working_directory }}

    - run: pip install twine
      shell: bash

    - name: Create tag
      uses: actions/github-script@v5
      with:
        github-token: ${{ inputs.GH_TOKEN }}
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ inputs.tag }}',
            sha: context.sha
          })
    - name: Publish wheel
      run: python -m twine upload ${{ inputs.working_directory }}/${{ inputs.artifact_name }}
      shell: bash
      env:
        TWINE_REPOSITORY_URL: ${{ inputs.destination_url }}
        TWINE_USERNAME: ${{ inputs.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ inputs.TWINE_PASSWORD }}
