on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      aws_role:
        required: true
        type: string
      container_image:
        required: true
        type: string
      cache_dir:
        default: '~/.cache'
        required: false
        type: string
      pip_dir:
        default: '~/.cache/pip'
        required: false
        type: string
      pre_commit_dir:
        default: '~/.cache/pre-commit'
        required: false
        type: string
      working_directory:
        default: '.'
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      PIP_EXTRA_INDEX_URL:
        required: true

jobs:
  status_checks:
    container:
      image: ${{ inputs.container_image }}
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    env:
      PIP_EXTRA_INDEX_URL: ${{ secrets.PIP_EXTRA_INDEX_URL }}
    runs-on: self-hosted
    steps:
      - name: Checkout Local
        uses: actions/checkout@v3

      - name: Configure Local
        run: git config --global --add safe.directory '*'

      - name: Cached Pip Install
        uses: AuroTFP/aurotfp-github-actions/.github/actions/cached-pip-install@master
        with:
          cache_dir: ${{ inputs.cache_dir }}
          extras: 'dev,test'
          pip_dir: ${{ inputs.pip_dir }}
          working_directory: ${{ inputs.working_directory }}

      - name: Make Pre Commit Dir
        shell: bash
        run: mkdir -p ${{ inputs.pre_commit_dir }}

      - name: Lint
        run: pre-commit run -a
        working-directory: ${{ inputs.working_directory }}
        env:
          PRE_COMMIT_HOME: ${{ inputs.pre_commit_dir }}

      - name: Pytest
        uses: AuroTFP/aurotfp-github-actions/.github/actions/test-pyproject@master
        with:
          aws_role: ${{ inputs.aws_role }}
          aws_region: ${{ inputs.aws_region }}
          pytest_args: --cov-report term-missing
          working_directory: ${{ inputs.working_directory }}
